-- EC Rental Property Management — Database Schema (Phase 2 + Inspections + Listings + Applications + Tenants)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, company TEXT DEFAULT '', email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, plan TEXT DEFAULT 'solo', property_limit INTEGER DEFAULT 5, role TEXT DEFAULT 'landlord', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS signups (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, company TEXT DEFAULT '', email TEXT NOT NULL, phone TEXT NOT NULL, property_count TEXT NOT NULL, plan TEXT NOT NULL, message TEXT DEFAULT '', status TEXT DEFAULT 'pending', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS properties (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, address TEXT NOT NULL, city TEXT DEFAULT '', state TEXT DEFAULT 'CA', zip TEXT DEFAULT '', rent_amount REAL DEFAULT 0, tenant_name TEXT DEFAULT '', tenant_email TEXT DEFAULT '', tenant_phone TEXT DEFAULT '', lease_start TEXT DEFAULT '', lease_end TEXT DEFAULT '', status TEXT DEFAULT 'vacant', notes TEXT DEFAULT '', created_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, type TEXT NOT NULL, amount REAL NOT NULL, description TEXT DEFAULT '', date TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS maintenance_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, tenant_name TEXT DEFAULT '', description TEXT NOT NULL, priority TEXT DEFAULT 'normal', status TEXT DEFAULT 'open', created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS inspections (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, inspector_name TEXT DEFAULT '', inspection_date TEXT NOT NULL, overall_condition TEXT DEFAULT '', summary TEXT DEFAULT '', status TEXT DEFAULT 'completed', created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS inspection_photos (id INTEGER PRIMARY KEY AUTOINCREMENT, inspection_id INTEGER NOT NULL, room_area TEXT NOT NULL, photo_data TEXT DEFAULT '', ai_analysis TEXT DEFAULT '', ai_condition TEXT DEFAULT '', ai_recommendation TEXT DEFAULT '', ai_repair_needed INTEGER DEFAULT 0, created_at TEXT NOT NULL, FOREIGN KEY (inspection_id) REFERENCES inspections(id));
CREATE TABLE IF NOT EXISTS listings (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, property_id INTEGER, title TEXT DEFAULT '', property_type TEXT NOT NULL DEFAULT 'HOUSE', street TEXT NOT NULL, unit TEXT DEFAULT '', city TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'CA', zip TEXT NOT NULL, rent REAL NOT NULL, deposit REAL DEFAULT 0, application_fee REAL DEFAULT 0, bedrooms INTEGER NOT NULL DEFAULT 0, full_baths INTEGER NOT NULL DEFAULT 1, half_baths INTEGER DEFAULT 0, square_feet INTEGER, date_available TEXT DEFAULT '', lease_term TEXT DEFAULT '12 Months', description TEXT DEFAULT '', amenities TEXT DEFAULT '', laundry TEXT DEFAULT '', parking_type TEXT DEFAULT '', cats_allowed INTEGER DEFAULT 0, small_dogs_allowed INTEGER DEFAULT 0, large_dogs_allowed INTEGER DEFAULT 0, smoking_allowed INTEGER DEFAULT 0, furnished INTEGER DEFAULT 0, contact_name TEXT DEFAULT '', contact_email TEXT NOT NULL, contact_phone TEXT NOT NULL, status TEXT DEFAULT 'draft', syndicate_zillow INTEGER DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
-- Extra listing fields kept beside listings so existing tables never need ALTER (bathroom: "", "private" or "shared", for room rentals).
CREATE TABLE IF NOT EXISTS listing_details (listing_id INTEGER PRIMARY KEY, bathroom TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS listing_photos (id INTEGER PRIMARY KEY AUTOINCREMENT, listing_id INTEGER NOT NULL, r2_key TEXT NOT NULL, caption TEXT DEFAULT '', sort_order INTEGER DEFAULT 0, created_at TEXT NOT NULL, FOREIGN KEY (listing_id) REFERENCES listings(id));
CREATE INDEX IF NOT EXISTS idx_listings_status ON listings(status, syndicate_zillow);
CREATE TABLE IF NOT EXISTS password_resets (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
-- "Continue with Google" sign ups waiting for the homepage form (src/google.ts). Tickets last 30 minutes.
CREATE TABLE IF NOT EXISTS google_signups (token_hash TEXT PRIMARY KEY, email TEXT NOT NULL, name TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS applications (id INTEGER PRIMARY KEY AUTOINCREMENT, listing_id INTEGER NOT NULL, landlord_user_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'new', screening_status TEXT NOT NULL DEFAULT 'not_started', first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL, move_in_date TEXT DEFAULT '', occupants INTEGER DEFAULT 1, current_address TEXT DEFAULT '', current_rent INTEGER DEFAULT 0, time_at_address TEXT DEFAULT '', current_landlord_name TEXT DEFAULT '', current_landlord_phone TEXT DEFAULT '', reason_for_moving TEXT DEFAULT '', employer TEXT DEFAULT '', job_title TEXT DEFAULT '', employer_phone TEXT DEFAULT '', employment_length TEXT DEFAULT '', monthly_income INTEGER DEFAULT 0, other_income TEXT DEFAULT '', pets TEXT DEFAULT '', vehicles TEXT DEFAULT '', additional_info TEXT DEFAULT '', signature_name TEXT NOT NULL, signed_at TEXT NOT NULL, signer_ip TEXT DEFAULT '', landlord_notes TEXT DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_applications_landlord ON applications(landlord_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_applications_listing ON applications(listing_id, email);
CREATE TABLE IF NOT EXISTS tenancies (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, landlord_user_id INTEGER NOT NULL, tenant_user_id INTEGER, email TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'invited', invite_token_hash TEXT, invite_expires_at TEXT, accepted_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE INDEX IF NOT EXISTS idx_tenancies_landlord ON tenancies(landlord_user_id, status);
CREATE INDEX IF NOT EXISTS idx_tenancies_tenant ON tenancies(tenant_user_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenancies_invite ON tenancies(invite_token_hash);

-- Landlord documents (leases, notices, invoices, receipts). data is the filled-in template as JSON.
CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, property_id INTEGER, tenancy_id INTEGER, doc_type TEXT NOT NULL, title TEXT NOT NULL, data TEXT NOT NULL DEFAULT '{}', shared_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_documents_user ON documents(user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_documents_tenancy ON documents(tenancy_id);

-- Cached map coordinates for listings (lat/lng NULL when the address couldn't be found).
CREATE TABLE IF NOT EXISTS listing_geo (listing_id INTEGER PRIMARY KEY, address TEXT NOT NULL, lat REAL, lng REAL, updated_at TEXT NOT NULL);
-- Inspections v2: inspection type, the move-in it's compared with, and saved photos (R2) with AI notes per photo.
CREATE TABLE IF NOT EXISTS inspection_details (inspection_id INTEGER PRIMARY KEY, type TEXT DEFAULT 'routine', compare_to INTEGER, comparison TEXT DEFAULT '', FOREIGN KEY (inspection_id) REFERENCES inspections(id));
CREATE TABLE IF NOT EXISTS inspection_items (id INTEGER PRIMARY KEY AUTOINCREMENT, inspection_id INTEGER NOT NULL, room_area TEXT NOT NULL, r2_key TEXT NOT NULL, condition TEXT DEFAULT '', notes TEXT DEFAULT '', repair_needed INTEGER DEFAULT 0, repair_item TEXT DEFAULT '', maintenance_id INTEGER, created_at TEXT NOT NULL, FOREIGN KEY (inspection_id) REFERENCES inspections(id));
CREATE INDEX IF NOT EXISTS idx_inspection_items_inspection ON inspection_items(inspection_id);

-- Stripe billing (src/billing.ts): one row per landlord account, kept in step by the Stripe webhook.
CREATE TABLE IF NOT EXISTS billing (user_id INTEGER PRIMARY KEY, customer_id TEXT, subscription_id TEXT, status TEXT NOT NULL DEFAULT 'none', plan TEXT, trial_end TEXT, period_end TEXT, cancel_at_period_end INTEGER DEFAULT 0, updated_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_billing_customer ON billing(customer_id);
-- Small site-wide settings the Worker saves for itself (e.g. the Stripe webhook signing secret it created).
CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);
-- Online rent payments (src/rent-payments.ts): each landlord's own Stripe account (one per test/live key), and each
-- tenant payment through Stripe Checkout. A paid payment is also written to transactions as rent.
CREATE TABLE IF NOT EXISTS payout_accounts (user_id INTEGER NOT NULL, mode TEXT NOT NULL, account_id TEXT NOT NULL, charges_enabled INTEGER DEFAULT 0, payouts_enabled INTEGER DEFAULT 0, details_submitted INTEGER DEFAULT 0, updated_at TEXT NOT NULL, PRIMARY KEY (user_id, mode), FOREIGN KEY (user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_payout_accounts_account ON payout_accounts(account_id);
CREATE TABLE IF NOT EXISTS rent_payments (id INTEGER PRIMARY KEY AUTOINCREMENT, tenancy_id INTEGER NOT NULL, property_id INTEGER NOT NULL, landlord_user_id INTEGER NOT NULL, tenant_user_id INTEGER NOT NULL, account_id TEXT NOT NULL, amount_cents INTEGER NOT NULL, period TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'started', method TEXT DEFAULT '', session_id TEXT, payment_intent TEXT, transaction_id INTEGER, failure TEXT DEFAULT '', created_at TEXT NOT NULL, paid_at TEXT, updated_at TEXT NOT NULL, FOREIGN KEY (tenancy_id) REFERENCES tenancies(id));
CREATE UNIQUE INDEX IF NOT EXISTS idx_rent_payments_session ON rent_payments(session_id);
CREATE INDEX IF NOT EXISTS idx_rent_payments_landlord ON rent_payments(landlord_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_rent_payments_tenancy ON rent_payments(tenancy_id, status);
-- Automatic rent reminders (src/rent-reminders.ts): each landlord's settings, and which reminders already went out.
CREATE TABLE IF NOT EXISTS rent_reminder_settings (user_id INTEGER PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 0, due_day INTEGER NOT NULL DEFAULT 1, days_before INTEGER NOT NULL DEFAULT 3, late_after INTEGER NOT NULL DEFAULT 5, updated_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS rent_reminder_log (tenancy_id INTEGER NOT NULL, period TEXT NOT NULL, kind TEXT NOT NULL, sent_at TEXT NOT NULL, PRIMARY KEY (tenancy_id, period, kind));
-- Remote AI inspections (/ai-inspection): anyone sends room photos, the AI reads them and the report link is emailed back.
CREATE TABLE IF NOT EXISTS remote_inspections (id INTEGER PRIMARY KEY AUTOINCREMENT, token TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT DEFAULT '', role TEXT DEFAULT '', address TEXT DEFAULT '', type TEXT DEFAULT 'routine', notes TEXT DEFAULT '', status TEXT DEFAULT 'open', overall TEXT DEFAULT '', summary TEXT DEFAULT '', created_at TEXT NOT NULL, finished_at TEXT);
CREATE TABLE IF NOT EXISTS remote_inspection_items (id INTEGER PRIMARY KEY AUTOINCREMENT, inspection_id INTEGER NOT NULL, room TEXT NOT NULL, r2_key TEXT NOT NULL, condition TEXT DEFAULT '', notes TEXT DEFAULT '', repair_needed INTEGER DEFAULT 0, repair_item TEXT DEFAULT '', created_at TEXT NOT NULL, FOREIGN KEY (inspection_id) REFERENCES remote_inspections(id));
CREATE INDEX IF NOT EXISTS idx_remote_inspection_items ON remote_inspection_items(inspection_id);
-- Visitor counts for /admin (src/visits.ts): one row per day, page, traffic source and device. No cookies, no IPs.
CREATE TABLE IF NOT EXISTS page_views (day TEXT NOT NULL, path TEXT NOT NULL, source TEXT NOT NULL, device TEXT NOT NULL, views INTEGER NOT NULL DEFAULT 0, visitors INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (day, path, source, device));
