-- EC Rental Property Management — Database Schema (Phase 2 + Inspections)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, company TEXT DEFAULT '', email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, plan TEXT DEFAULT 'solo', property_limit INTEGER DEFAULT 5, role TEXT DEFAULT 'landlord', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS signups (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, company TEXT DEFAULT '', email TEXT NOT NULL, phone TEXT NOT NULL, property_count TEXT NOT NULL, plan TEXT NOT NULL, message TEXT DEFAULT '', status TEXT DEFAULT 'pending', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS properties (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, address TEXT NOT NULL, city TEXT DEFAULT '', state TEXT DEFAULT 'CA', zip TEXT DEFAULT '', rent_amount REAL DEFAULT 0, tenant_name TEXT DEFAULT '', tenant_email TEXT DEFAULT '', tenant_phone TEXT DEFAULT '', lease_start TEXT DEFAULT '', lease_end TEXT DEFAULT '', status TEXT DEFAULT 'vacant', notes TEXT DEFAULT '', created_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, type TEXT NOT NULL, amount REAL NOT NULL, description TEXT DEFAULT '', date TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS maintenance_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, tenant_name TEXT DEFAULT '', description TEXT NOT NULL, priority TEXT DEFAULT 'normal', status TEXT DEFAULT 'open', created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS inspections (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, inspector_name TEXT DEFAULT '', inspection_date TEXT NOT NULL, overall_condition TEXT DEFAULT '', summary TEXT DEFAULT '', status TEXT DEFAULT 'completed', created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS inspection_photos (id INTEGER PRIMARY KEY AUTOINCREMENT, inspection_id INTEGER NOT NULL, room_area TEXT NOT NULL, photo_data TEXT DEFAULT '', ai_analysis TEXT DEFAULT '', ai_condition TEXT DEFAULT '', ai_recommendation TEXT DEFAULT '', ai_repair_needed INTEGER DEFAULT 0, created_at TEXT NOT NULL, FOREIGN KEY (inspection_id) REFERENCES inspections(id));
CREATE TABLE IF NOT EXISTS password_resets (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
