-- EC Rental Property Management — Database Schema (Phase 2 + Inspections + Listings + Applications)

CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, company TEXT DEFAULT '', email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, plan TEXT DEFAULT 'solo', property_limit INTEGER DEFAULT 5, role TEXT DEFAULT 'landlord', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS signups (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, company TEXT DEFAULT '', email TEXT NOT NULL, phone TEXT NOT NULL, property_count TEXT NOT NULL, plan TEXT NOT NULL, message TEXT DEFAULT '', status TEXT DEFAULT 'pending', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS properties (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, address TEXT NOT NULL, city TEXT DEFAULT '', state TEXT DEFAULT 'CA', zip TEXT DEFAULT '', rent_amount REAL DEFAULT 0, tenant_name TEXT DEFAULT '', tenant_email TEXT DEFAULT '', tenant_phone TEXT DEFAULT '', lease_start TEXT DEFAULT '', lease_end TEXT DEFAULT '', status TEXT DEFAULT 'vacant', notes TEXT DEFAULT '', created_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, type TEXT NOT NULL, amount REAL NOT NULL, description TEXT DEFAULT '', date TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS maintenance_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, tenant_name TEXT DEFAULT '', description TEXT NOT NULL, priority TEXT DEFAULT 'normal', status TEXT DEFAULT 'open', created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS inspections (id INTEGER PRIMARY KEY AUTOINCREMENT, property_id INTEGER NOT NULL, inspector_name TEXT DEFAULT '', inspection_date TEXT NOT NULL, overall_condition TEXT DEFAULT '', summary TEXT DEFAULT '', status TEXT DEFAULT 'completed', created_at TEXT NOT NULL, FOREIGN KEY (property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS inspection_photos (id INTEGER PRIMARY KEY AUTOINCREMENT, inspection_id INTEGER NOT NULL, room_area TEXT NOT NULL, photo_data TEXT DEFAULT '', ai_analysis TEXT DEFAULT '', ai_condition TEXT DEFAULT '', ai_recommendation TEXT DEFAULT '', ai_repair_needed INTEGER DEFAULT 0, created_at TEXT NOT NULL, FOREIGN KEY (inspection_id) REFERENCES inspections(id));
CREATE TABLE IF NOT EXISTS listings (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, property_id INTEGER, title TEXT DEFAULT '', property_type TEXT NOT NULL DEFAULT 'HOUSE', street TEXT NOT NULL, unit TEXT DEFAULT '', city TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'CA', zip TEXT NOT NULL, rent REAL NOT NULL, deposit REAL DEFAULT 0, application_fee REAL DEFAULT 0, bedrooms INTEGER NOT NULL DEFAULT 0, full_baths INTEGER NOT NULL DEFAULT 1, half_baths INTEGER DEFAULT 0, square_feet INTEGER, date_available TEXT DEFAULT '', lease_term TEXT DEFAULT '12 Months', description TEXT DEFAULT '', amenities TEXT DEFAULT '', laundry TEXT DEFAULT '', parking_type TEXT DEFAULT '', cats_allowed INTEGER DEFAULT 0, small_dogs_allowed INTEGER DEFAULT 0, large_dogs_allowed INTEGER DEFAULT 0, smoking_allowed INTEGER DEFAULT 0, furnished INTEGER DEFAULT 0, contact_name TEXT DEFAULT '', contact_email TEXT NOT NULL, contact_phone TEXT NOT NULL, status TEXT DEFAULT 'draft', syndicate_zillow INTEGER DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS listing_photos (id INTEGER PRIMARY KEY AUTOINCREMENT, listing_id INTEGER NOT NULL, r2_key TEXT NOT NULL, caption TEXT DEFAULT '', sort_order INTEGER DEFAULT 0, created_at TEXT NOT NULL, FOREIGN KEY (listing_id) REFERENCES listings(id));
CREATE INDEX IF NOT EXISTS idx_listings_status ON listings(status, syndicate_zillow);
CREATE TABLE IF NOT EXISTS password_resets (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS applications (id INTEGER PRIMARY KEY AUTOINCREMENT, listing_id INTEGER NOT NULL, landlord_user_id INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'new', screening_status TEXT NOT NULL DEFAULT 'not_started', first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL, move_in_date TEXT DEFAULT '', occupants INTEGER DEFAULT 1, current_address TEXT DEFAULT '', current_rent INTEGER DEFAULT 0, time_at_address TEXT DEFAULT '', current_landlord_name TEXT DEFAULT '', current_landlord_phone TEXT DEFAULT '', reason_for_moving TEXT DEFAULT '', employer TEXT DEFAULT '', job_title TEXT DEFAULT '', employer_phone TEXT DEFAULT '', employment_length TEXT DEFAULT '', monthly_income INTEGER DEFAULT 0, other_income TEXT DEFAULT '', pets TEXT DEFAULT '', vehicles TEXT DEFAULT '', additional_info TEXT DEFAULT '', signature_name TEXT NOT NULL, signed_at TEXT NOT NULL, signer_ip TEXT DEFAULT '', landlord_notes TEXT DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_applications_landlord ON applications(landlord_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_applications_listing ON applications(listing_id, email);
