name = "ec-rental-landing-page"
main = "src/index.ts"
compatibility_date = "2026-09-25"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "ec-rental-db"
database_id = "80e01fdc-9511-4868-9b82-e803290e7700"
